  
language: go
go: 
 - 1.14.3

script:
 - go test

services:
  - docker

before_install:
  #Update docker latest
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

  # Build the image
  - docker build -t bot .
  - docker run -it --rm --env-file=.env --name mybot bot
